FROM python:3.8
ENV PYTHONUNBUFFERED 1

RUN apt-get update && apt-get install -y gettext libgettextpo-dev

COPY ./requirements.txt /requirements.txt
RUN pip3 install --upgrade pip
RUN pip3 install --upgrade -r /requirements.txt

ADD . /FlaskAPI-Blog
WORKDIR /FlaskAPI-Blog

CMD [ "uwsgi", "--ini", "app.ini" ]

ENV WAIT_VERSION 2.7.2
ENV FLASK_ENV = "development"
ENV PORT 8000

ADD https://github.com/ufoscout/docker-compose-wait/releases/download/$WAIT_VERSION/wait /wait
RUN chmod +x /wait

COPY ./entrypoint.dev.sh /entrypoint.dev.sh
RUN chmod +x /entrypoint.dev.sh

CMD ["/entrypoint.dev.sh"]