version: '3.7'

volumes:
  db:


networks:
  diplom-project_univer-net:
   external: true

services:
  registerservice:
    container_name: registerservice
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/FlaskAPI-Blog
    env_file:
      - ./.env.prod.dev
    ports:
      - "8889:8889"
    depends_on:
      - db
    networks:
      - diplom-project_univer-net


  db:
    restart: always
    image: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - ./.env.prod.db
    ports:
      - "5435:5435"
    networks:
      - diplom-project_univer-net

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: zaysan
    ports:
      - "5050:80"
    networks:
      - diplom-project_univer-net