"""empty message

Revision ID: 4dc40be2677a
Revises: fde5db381185
Create Date: 2022-04-25 04:13:09.089705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dc40be2677a'
down_revision = 'fde5db381185'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('speciality', sa.Column('name_en', sa.String(length=500), nullable=True))
    op.add_column('speciality', sa.Column('name_kk', sa.String(length=500), nullable=False))
    op.drop_column('speciality', 'name')
    op.add_column('users', sa.Column('full_name_en', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('full_name_kk', sa.String(length=255), nullable=True))
    op.drop_column('users', 'name')
    op.drop_column('users', 'surname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('surname', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('users', 'full_name_kk')
    op.drop_column('users', 'full_name_en')
    op.add_column('speciality', sa.Column('name', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    op.drop_column('speciality', 'name_kk')
    op.drop_column('speciality', 'name_en')
    # ### end Alembic commands ###
