"""empty message

Revision ID: 8864b8ad3d1b
Revises: 
Create Date: 2022-04-17 16:37:21.533379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8864b8ad3d1b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('course', sa.Enum('first', 'second', 'third', 'fourth', name='coursechoices'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'course')
    # ### end Alembic commands ###
