"""empty message

Revision ID: fde5db381185
Revises: 936c0d21f033
Create Date: 2022-04-23 12:21:35.843674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fde5db381185'
down_revision = '936c0d21f033'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('speciality', sa.Column('code', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('speciality', 'code')
    # ### end Alembic commands ###
